/**
 * AuraMed+ Pharmacy & Healthcare Database
 * Comprehensive catalog of authentic pharmaceuticals, OTC, health devices and wellness products.
 */

const MEDICINES_DATABASE = [
  {
    id: "med-1",
    name: "Paracetamol Advance Fast-Acting",
    genericName: "Paracetamol / Acetaminophen",
    brand: "GSK Healthcare",
    category: "pain-relief",
    categoryLabel: "Pain & Fever",
    dosage: "500mg - 20 Tablets",
    price: 4.99,
    originalPrice: 6.99,
    rating: 4.9,
    reviewsCount: 342,
    requiresRx: false,
    inStock: true,
    badge: "Bestseller",
    description: "Rapid relief for mild to moderate pain including headache, migraine, toothache, muscle aches, and fever reduction. Formulated with Optizorb technology for 5x faster absorption.",
    activeIngredients: "Paracetamol 500mg per tablet",
    usageAdvice: "Take 1-2 tablets every 4 to 6 hours as needed. Do not exceed 8 tablets in 24 hours.",
    sideEffects: "Rare when taken as directed. Allergic reactions or liver toxicity if overdosed.",
    temperatureControl: "Store below 25°C",
    imageType: "pill",
    colorGradient: "from-blue-500 to-indigo-600"
  },
  {
    id: "med-2",
    name: "AmoxiClav Broad-Spectrum",
    genericName: "Amoxicillin + Potassium Clavulanate",
    brand: "Novartis Pharma",
    category: "antibiotics",
    categoryLabel: "Antibiotics",
    dosage: "625mg - 10 Film-Coated Tablets",
    price: 18.50,
    originalPrice: 22.00,
    rating: 4.8,
    reviewsCount: 189,
    requiresRx: true,
    inStock: true,
    badge: "Rx Required",
    description: "Prescription penicillin antibiotic combined with a beta-lactamase inhibitor to treat bacterial infections of the respiratory tract, ear, sinus, skin, and urinary tract.",
    activeIngredients: "Amoxicillin 500mg, Clavulanic Acid 125mg",
    usageAdvice: "Strictly as prescribed by a licensed physician. Complete the full course even if symptoms subside.",
    sideEffects: "Mild diarrhea, nausea, stomach discomfort.",
    temperatureControl: "Store in a cool, dry place away from direct sunlight",
    imageType: "capsule",
    colorGradient: "from-emerald-500 to-teal-700"
  },
  {
    id: "med-3",
    name: "LipidCare Atorvastatin",
    genericName: "Atorvastatin Calcium",
    brand: "Pfizer Labs",
    category: "chronic-care",
    categoryLabel: "Cardiovascular & BP",
    dosage: "20mg - 30 Film-Coated Tablets",
    price: 14.75,
    originalPrice: 19.99,
    rating: 4.9,
    reviewsCount: 276,
    requiresRx: true,
    inStock: true,
    badge: "Doctor Choice",
    description: "HMG-CoA reductase inhibitor (statin) used alongside diet to reduce LDL bad cholesterol and triglycerides, significantly lowering risk of heart disease and stroke.",
    activeIngredients: "Atorvastatin Calcium 20mg",
    usageAdvice: "Take one tablet once daily at the same time every evening, with or without food.",
    sideEffects: "Muscle soreness, digestive issues, mild headache.",
    temperatureControl: "Store at 20°C to 25°C",
    imageType: "tablet",
    colorGradient: "from-rose-500 to-pink-600"
  },
  {
    id: "med-4",
    name: "Glucovance Metformin XR",
    genericName: "Metformin Hydrochloride Extended-Release",
    brand: "Merck Group",
    category: "chronic-care",
    categoryLabel: "Diabetes Care",
    dosage: "500mg - 60 Extended Release Tablets",
    price: 12.20,
    originalPrice: 15.50,
    rating: 4.8,
    reviewsCount: 412,
    requiresRx: true,
    inStock: true,
    badge: "Daily Essential",
    description: "First-line oral anti-hyperglycemic agent for Type 2 Diabetes mellitus. Helps restore your body's proper response to insulin and reduces hepatic glucose production.",
    activeIngredients: "Metformin HCl 500mg Extended Release",
    usageAdvice: "Swallow whole with an evening meal. Do not crush or chew.",
    sideEffects: "Mild metallic taste, transient nausea, stomach upset.",
    temperatureControl: "Store at room temperature 15°C to 30°C",
    imageType: "tablet",
    colorGradient: "from-purple-500 to-indigo-700"
  },
  {
    id: "med-5",
    name: "AeroHist Cetirizine 24H",
    genericName: "Cetirizine Hydrochloride",
    brand: "Johnson & Johnson",
    category: "pain-relief",
    categoryLabel: "Allergy & Cold",
    dosage: "10mg - 30 Film-Coated Tablets",
    price: 7.95,
    originalPrice: 10.50,
    rating: 4.9,
    reviewsCount: 520,
    requiresRx: false,
    inStock: true,
    badge: "Non-Drowsy",
    description: "2nd generation antihistamine providing 24-hour relief from seasonal allergies, hay fever, sneezing, runny nose, itchy throat, and allergic skin hives.",
    activeIngredients: "Cetirizine HCl 10mg",
    usageAdvice: "Take 1 tablet once daily with water. Can be taken with or without food.",
    sideEffects: "Slight dry mouth; rarely causes drowsiness.",
    temperatureControl: "Store below 25°C",
    imageType: "pill",
    colorGradient: "from-cyan-500 to-blue-600"
  },
  {
    id: "med-6",
    name: "GastroShield Omeprazole",
    genericName: "Omeprazole Delayed-Release",
    brand: "AstraZeneca",
    category: "pain-relief",
    categoryLabel: "Digestive & Acid Reflux",
    dosage: "20mg - 28 Gastro-Resistant Capsules",
    price: 11.40,
    originalPrice: 14.80,
    rating: 4.7,
    reviewsCount: 310,
    requiresRx: false,
    inStock: true,
    badge: "Acid Relief",
    description: "Proton Pump Inhibitor (PPI) that suppresses stomach acid production, treating heartburn, GERD, gastric ulcers, and acid indigestion effectively.",
    activeIngredients: "Omeprazole 20mg in enteric-coated pellets",
    usageAdvice: "Take 1 capsule in the morning at least 30 to 60 minutes before breakfast.",
    sideEffects: "Headache, mild stomach discomfort.",
    temperatureControl: "Store in moisture-proof blister below 25°C",
    imageType: "capsule",
    colorGradient: "from-amber-500 to-orange-600"
  },
  {
    id: "med-7",
    name: "ImmunoBoost Zinc + Vitamin C 1000",
    genericName: "Ascorbic Acid + Zinc Citrate + Vitamin D3",
    brand: "NutriLife Bio",
    category: "vitamins",
    categoryLabel: "Vitamins & Immunity",
    dosage: "20 Effervescent Orange Tablets",
    price: 8.99,
    originalPrice: 12.00,
    rating: 4.9,
    reviewsCount: 680,
    requiresRx: false,
    inStock: true,
    badge: "Top Rated",
    description: "Triple-action immune defense formula. Rapid effervescent absorption delivers 1000mg pure Vitamin C, 15mg Elemental Zinc, and 1000 IU Vitamin D3.",
    activeIngredients: "Ascorbic Acid 1000mg, Zinc Citrate 15mg, Vit D3 1000IU",
    usageAdvice: "Dissolve 1 tablet in 200ml cold water once daily after food.",
    sideEffects: "Well tolerated. Excess intake may cause mild loose stools.",
    temperatureControl: "Keep tube tightly sealed in dry place",
    imageType: "effervescent",
    colorGradient: "from-yellow-400 to-amber-600"
  },
  {
    id: "med-8",
    name: "Omron Smart Upper Arm BP Monitor",
    genericName: "Automated Digital Sphygmomanometer",
    brand: "Omron Healthcare",
    category: "devices",
    categoryLabel: "Medical Devices",
    dosage: "HEM-7120 with IntelliSense Cuff",
    price: 49.99,
    originalPrice: 65.00,
    rating: 5.0,
    reviewsCount: 840,
    requiresRx: false,
    inStock: true,
    badge: "Clinical Accuracy",
    description: "Clinically certified upper arm blood pressure monitor. Features Intellisense automatic inflation, irregular heartbeat detection, and cuff wrap guide with memory storage.",
    activeIngredients: "Digital Oscillometric Sensor, Latex-free comfort cuff (22-32 cm)",
    usageAdvice: "Sit comfortably and rest 5 minutes before measurement. Keep arm level with heart.",
    sideEffects: "None",
    temperatureControl: "Keep in protective carrying case",
    imageType: "device",
    colorGradient: "from-sky-600 to-blue-800"
  },
  {
    id: "med-9",
    name: "Accu-Chek Instant Blood Glucose Kit",
    genericName: "Blood Glucose Monitoring System",
    brand: "Roche Diagnostics",
    category: "devices",
    categoryLabel: "Diabetes Monitors",
    dosage: "1 Meter + 25 Test Strips + 10 Lancets",
    price: 29.50,
    originalPrice: 38.00,
    rating: 4.8,
    reviewsCount: 512,
    requiresRx: false,
    inStock: true,
    badge: "Instant Results",
    description: "Effortless glucose testing with intuitive target range indicator. Requires a tiny 0.6 µL blood droplet and yields lab-precise readings within 4 seconds.",
    activeIngredients: "Electrochemical FAD-GDH sensor technology",
    usageAdvice: "Insert test strip, apply blood sample, read results. Pair with mySugr app.",
    sideEffects: "None",
    temperatureControl: "Store strips between 4°C and 30°C",
    imageType: "device",
    colorGradient: "from-teal-600 to-cyan-800"
  },
  {
    id: "med-10",
    name: "IbuPro Ultra Anti-Inflammatory",
    genericName: "Ibuprofen Liquid Filled Softgels",
    brand: "Abbott Health",
    category: "pain-relief",
    categoryLabel: "Pain Relief",
    dosage: "400mg - 24 Softgels",
    price: 6.49,
    originalPrice: 8.50,
    rating: 4.8,
    reviewsCount: 290,
    requiresRx: false,
    inStock: true,
    badge: "Fast Liquid Gel",
    description: "NSAID providing targeted relief for acute back pain, joint stiffness, menstrual cramps, dental pain, and muscular inflammation.",
    activeIngredients: "Solubilized Ibuprofen 400mg",
    usageAdvice: "Take 1 softgel every 6 to 8 hours with meals or milk. Do not take on an empty stomach.",
    sideEffects: "Gastrointestinal discomfort if taken without food.",
    temperatureControl: "Store below 25°C",
    imageType: "capsule",
    colorGradient: "from-red-500 to-rose-700"
  },
  {
    id: "med-11",
    name: "CeraDerm Ceramide Barrier Cream",
    genericName: "Essential Ceramides 1, 3, 6-II + Hyaluronic Acid",
    brand: "DermoLab Paris",
    category: "skincare",
    categoryLabel: "Dermatological Care",
    dosage: "177ml Dispenser Bottle",
    price: 16.90,
    originalPrice: 21.00,
    rating: 4.9,
    reviewsCount: 620,
    requiresRx: false,
    inStock: true,
    badge: "Dermatologist Approved",
    description: "Fragrance-free barrier repair moisturizing cream for dry, compromised, eczema-prone skin. Non-comedogenic MVE continuous hydration technology.",
    activeIngredients: "Ceramides 1, 3, 6-II, Hyaluronic Acid, Niacinamide",
    usageAdvice: "Apply liberally to clean face and body as often as needed.",
    sideEffects: "Hypoallergenic. Zero fragrance.",
    temperatureControl: "Store at ambient room temperature",
    imageType: "bottle",
    colorGradient: "from-sky-400 to-indigo-500"
  },
  {
    id: "med-12",
    name: "BabyGuard Calming Organic Wash",
    genericName: "Calendula & Colloidal Oat Wash",
    brand: "Mustela Pure",
    category: "baby",
    categoryLabel: "Mother & Baby",
    dosage: "250ml Pump Bottle",
    price: 13.50,
    originalPrice: 17.00,
    rating: 5.0,
    reviewsCount: 198,
    requiresRx: false,
    inStock: true,
    badge: "Pediatrician Tested",
    description: "Ultra-mild tear-free 2-in-1 hair and body cleanser formulated specifically for sensitive newborn delicate skin. Free from sulfates, parabens and phthalates.",
    activeIngredients: "Organic Calendula Extract, Colloidal Oatmeal, Chamomile",
    usageAdvice: "Pump onto hands or soft washcloth, lather gently onto baby's skin and hair, rinse.",
    sideEffects: "Tearless and hypoallergenic.",
    temperatureControl: "Store away from intense heat",
    imageType: "bottle",
    colorGradient: "from-emerald-400 to-teal-600"
  },
  {
    id: "med-13",
    name: "PulseGuard OLED Fingertip Oximeter",
    genericName: "Digital Blood Oxygen Saturation Monitor",
    brand: "Apex Medical",
    category: "devices",
    categoryLabel: "Medical Devices",
    dosage: "SpO2 & Pulse Rate with Lanyard & Batteries",
    price: 19.99,
    originalPrice: 28.00,
    rating: 4.8,
    reviewsCount: 380,
    requiresRx: false,
    inStock: true,
    badge: "Essential",
    description: "Dual-color high-definition OLED display measuring Blood Oxygen Saturation (SpO2) and Pulse Rate accurately within 5 seconds. Audio alarm for low saturation.",
    activeIngredients: "Infrared Optical Sensor, Hypoallergenic silicone finger chamber",
    usageAdvice: "Warm cold fingertips before inserting finger. Remain still during reading.",
    sideEffects: "None",
    temperatureControl: "Store in moisture-free case",
    imageType: "device",
    colorGradient: "from-cyan-600 to-slate-800"
  },
  {
    id: "med-14",
    name: "BioRelief First Aid Medical Trauma Kit",
    genericName: "Emergency Comprehensive First Aid Kit",
    brand: "RedCross Authorized",
    category: "devices",
    categoryLabel: "First Aid & Emergency",
    dosage: "65-Piece Waterproof Hard Case",
    price: 24.90,
    originalPrice: 32.00,
    rating: 4.9,
    reviewsCount: 420,
    requiresRx: false,
    inStock: true,
    badge: "Safety Essential",
    description: "Hospital-grade emergency response kit containing sterile gauze pads, antiseptic swabs, burn dressing, emergency tourniquet, trauma shears, bandages, and CPR shield.",
    activeIngredients: "Povidone Iodine, Sterile Hydrogel, Cohesive Elastic Bandages",
    usageAdvice: "Keep accessible in cars, homes, offices and outdoor activities.",
    sideEffects: "None",
    temperatureControl: "Store in cool dry space",
    imageType: "box",
    colorGradient: "from-rose-600 to-red-800"
  },
  {
    id: "med-15",
    name: "NeuroCalm Magnesium Glycinate 500",
    genericName: "Chelated Magnesium Bisglycinate + L-Theanine",
    brand: "PureLabs Naturals",
    category: "vitamins",
    categoryLabel: "Vitamins & Supplements",
    dosage: "90 Vegetarian Capsules",
    price: 15.80,
    originalPrice: 20.00,
    rating: 4.9,
    reviewsCount: 710,
    requiresRx: false,
    inStock: true,
    badge: "Sleep & Muscle",
    description: "Highly bioavailable non-laxative chelated magnesium for deep restorative sleep, muscular relaxation, nerve support, and anxiety reduction.",
    activeIngredients: "Magnesium Bisglycinate 400mg, L-Theanine 100mg",
    usageAdvice: "Take 2 capsules 30 to 45 minutes before sleep with water.",
    sideEffects: "Extremely gentle on digestion.",
    temperatureControl: "Keep container tightly closed",
    imageType: "capsule",
    colorGradient: "from-violet-500 to-purple-800"
  },
  {
    id: "med-16",
    name: "BronchoClear Ivy Herb Cough Elixir",
    genericName: "Hedera Helix (English Ivy Leaf) Extract",
    brand: "Prospan Herbal",
    category: "pain-relief",
    categoryLabel: "Cold & Cough",
    dosage: "100ml Syrup with Measuring Cup",
    price: 9.75,
    originalPrice: 12.50,
    rating: 4.8,
    reviewsCount: 330,
    requiresRx: false,
    inStock: true,
    badge: "Sugar-Free",
    description: "Natural herbal mucolytic and bronchodilator. Liquefies stubborn mucus, calms coughing spasms, and eases airway breathing without causing drowsiness.",
    activeIngredients: "Standardized Ivy Leaf Extract 7mg/ml",
    usageAdvice: "Adults: 5ml to 7.5ml three times daily. Children (6-12y): 5ml twice daily.",
    sideEffects: "Non-sedating, zero alcohol, zero artificial coloring.",
    temperatureControl: "Store below 25°C",
    imageType: "bottle",
    colorGradient: "from-emerald-500 to-green-700"
  }
];

const HEALTH_ARTICLES = [
  {
    id: "article-1",
    tag: "Medication Safety",
    title: "Generic vs. Brand Name Medicines: What You Need to Know",
    excerpt: "Learn why FDA-approved generic medicines contain the identical active ingredients, potency, and safety as high-priced brand names.",
    readTime: "4 min read",
    author: "Dr. Sarah Lin, PharmD",
    date: "Sep 28, 2026"
  },
  {
    id: "article-2",
    tag: "Clinical Guide",
    title: "Why You Must Finish Your Full Antibiotic Course",
    excerpt: "Stopping your antibiotics early creates resistant superbugs. Discover how clinical adherence protects your long-term immunity.",
    readTime: "5 min read",
    author: "Dr. Arthur Bennett, Senior Physician",
    date: "Sep 20, 2026"
  },
  {
    id: "article-3",
    tag: "Home Healthcare",
    title: "How to Accurately Measure Blood Pressure at Home",
    excerpt: "Step-by-step guidance on cuff placement, timing, resting posture, and logging readings for your cardiologist.",
    readTime: "3 min read",
    author: "Elena Rostova, Lead Pharmacist",
    date: "Sep 15, 2026"
  }
];

const STORE_BRANCHES = [
  {
    name: "AuraMed Central Flagship & 24/7 Drive-Thru",
    address: "742 Healthcare Boulevard, Medical District",
    phone: "(800) 555-2872",
    hours: "Open 24 Hours / 7 Days",
    features: ["Cold-Chain Vault", "24/7 Pharmacist On-Site", "Drive-Thru Window", "Express Lab Pickup"]
  },
  {
    name: "AuraMed Westside Wellness Center",
    address: "1208 Elmwood Park Ave, West Plaza",
    phone: "(800) 555-2875",
    hours: "Mon - Sat: 7:00 AM - 11:00 PM | Sun: 8:00 AM - 9:00 PM",
    features: ["Prescription Consultations", "Diabetes Care Hub", "Home Delivery Base"]
  },
  {
    name: "AuraMed Northside Health Clinic Branch",
    address: "3305 Highland Ridge Way, Suite 100",
    phone: "(800) 555-2879",
    hours: "Mon - Sun: 8:00 AM - 10:00 PM",
    features: ["Vaccination Center", "Medical Device Fitting", "Fast Rx Collection"]
  }
];
